### ISSUE TITLE
Forwarder only seems to send DHCPACK

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence-dhcp-forwarder#6]
From the deployment I've done, the DHCP forwarder only seems to send the DHCPACK from the DHCP server.

Although we can make SSO + update_iplog occur on it via configuration, the fingerprinting only occurs on a DHCPREQUEST, meaning my deployment lost fingerprinting capabilities because of that.

First, was it designed to only send the ACK ?
Second, can we make it send the REQUEST by default ?
Third, how can I adjust the deployment to have the REQUEST as well without re-installing the sensor ?

**Comment by tlaurion** [comment]
The filter line is the [following](https://github.com/inverse-inc/packetfence-dhcp-forwarder/blob/master/dhcp-forwarder-config-generator/main.go#L29).

One difference of the code is that the port changed from 67 to 68, but DHCPREQ and DHCPACK are supposed to occur between port 67 and port 68.

In your deployment, can you modify "C:\Program Files (x86)\DHCP Forwarder\DHCP-Forwarder.toml" so that the filter line looks like this:
`
Filter = "udp and port 67 and ((udp[250:1] = 0x3) or (udp[250:1] = 0x5))"
`
And then restart the service?

**Comment by julsemaan** [comment]
Confirmed as fixed on the deployment using the corrected filter
